var COMPACT = [
  ['01','00','Prov. Aceh','Provinsi Aceh'],
  ['01','01','Kab. Aceh Barat','Provinsi Aceh'],
  ['01','02','Kab. Aceh Besar','Provinsi Aceh'],
  ['01','03','Kab. Aceh Selatan','Provinsi Aceh'],
  ['01','04','Kab. Aceh Singkil','Provinsi Aceh'],
  ['01','05','Kab. Aceh Tengah','Provinsi Aceh'],
  ['01','06','Kab. Aceh Tenggara','Provinsi Aceh'],
  ['01','07','Kab. Aceh Timur','Provinsi Aceh'],
  ['01','08','Kab. Aceh Utara','Provinsi Aceh'],
  ['01','09','Kab. Bireuen','Provinsi Aceh'],
  ['01','10','Kab. Pidie','Provinsi Aceh'],
  ['01','11','Kab. Simeulue','Provinsi Aceh'],
  ['01','12','Kota Banda Aceh','Provinsi Aceh'],
  ['01','13','Kota Sabang','Provinsi Aceh'],
  ['01','14','Kota Langsa','Provinsi Aceh'],
  ['01','15','Kota Lhokseumawe','Provinsi Aceh'],
  ['01','16','Kab. Gayo Lues','Provinsi Aceh'],
  ['01','17','Kab. Aceh Barat Daya','Provinsi Aceh'],
  ['01','18','Kab. Aceh Jaya','Provinsi Aceh'],
  ['01','19','Kab. Nagan Raya','Provinsi Aceh'],
  ['01','20','Kab. Aceh Tamiang','Provinsi Aceh'],
  ['01','21','Kab. Bener Meriah','Provinsi Aceh'],
  ['01','22','Kab. Pidie Jaya','Provinsi Aceh'],
  ['01','23','Kota Subulussalam','Provinsi Aceh'],
  ['02','00','Prov. Sumatera Utara','Provinsi Sumatera Utara'],
  ['02','01','Kab. Asahan','Provinsi Sumatera Utara'],
  ['02','02','Kab. Dairi','Provinsi Sumatera Utara'],
  ['02','03','Kab. Deli Serdang','Provinsi Sumatera Utara'],
  ['02','04','Kab. Karo','Provinsi Sumatera Utara'],
  ['02','05','Kab. Labuhanbatu','Provinsi Sumatera Utara'],
  ['02','06','Kab. Langkat','Provinsi Sumatera Utara'],
  ['02','07','Kab. Mandailing Natal','Provinsi Sumatera Utara'],
  ['02','08','Kab. Nias','Provinsi Sumatera Utara'],
  ['02','09','Kab. Simalungun','Provinsi Sumatera Utara'],
  ['02','10','Kab. Tapanuli Selatan','Provinsi Sumatera Utara'],
  ['02','11','Kab. Tapanuli Tengah','Provinsi Sumatera Utara'],
  ['02','12','Kab. Tapanuli Utara','Provinsi Sumatera Utara'],
  ['02','13','Kab. Toba Samosir','Provinsi Sumatera Utara'],
  ['02','14','Kota Binjai','Provinsi Sumatera Utara'],
  ['02','15','Kota Medan','Provinsi Sumatera Utara'],
  ['02','16','Kota Pematang Siantar','Provinsi Sumatera Utara'],
  ['02','17','Kota Sibolga','Provinsi Sumatera Utara'],
  ['02','18','Kota Tanjung Balai','Provinsi Sumatera Utara'],
  ['02','19','Kota Tebing Tinggi','Provinsi Sumatera Utara'],
  ['02','20','Kota Padang Sidempuan','Provinsi Sumatera Utara'],
  ['02','21','Kab. Pakpak Bharat','Provinsi Sumatera Utara'],
  ['02','22','Kab. Nias Selatan','Provinsi Sumatera Utara'],
  ['02','23','Kab. Humbang Hasundutan','Provinsi Sumatera Utara'],
  ['02','24','Kab. Serdang Bedagai','Provinsi Sumatera Utara'],
  ['02','25','Kab. Samosir','Provinsi Sumatera Utara'],
  ['02','26','Kab. Batu Bara','Provinsi Sumatera Utara'],
  ['02','27','Kab. Padang Lawas','Provinsi Sumatera Utara'],
  ['02','28','Kab. Padang Lawas Utara','Provinsi Sumatera Utara'],
  ['02','29','Kab. Labuhanbatu Selatan','Provinsi Sumatera Utara'],
  ['02','30','Kab. Labuhanbatu Utara','Provinsi Sumatera Utara'],
  ['02','31','Kab. Nias Utara','Provinsi Sumatera Utara'],
  ['02','32','Kab. Nias Barat','Provinsi Sumatera Utara'],
  ['02','33','Kota Gunungsitoli','Provinsi Sumatera Utara'],
  ['03','00','Prov. Sumatera Barat','Provinsi Sumatera Barat'],
  ['03','01','Kab. Limapuluh Kota','Provinsi Sumatera Barat'],
  ['03','02','Kab. Agam','Provinsi Sumatera Barat'],
  ['03','03','Kab. Kepulauan Mentawai','Provinsi Sumatera Barat'],
  ['03','04','Kab. Padang Pariaman','Provinsi Sumatera Barat'],
  ['03','05','Kab. Pasaman','Provinsi Sumatera Barat'],
  ['03','06','Kab. Pesisir Selatan','Provinsi Sumatera Barat'],
  ['03','07','Kab. Sijunjung','Provinsi Sumatera Barat'],
  ['03','08','Kab. Solok','Provinsi Sumatera Barat'],
  ['03','09','Kab. Tanah Datar','Provinsi Sumatera Barat'],
  ['03','10','Kota Bukit Tinggi','Provinsi Sumatera Barat'],
  ['03','11','Kota Padang Panjang','Provinsi Sumatera Barat'],
  ['03','12','Kota Padang','Provinsi Sumatera Barat'],
  ['03','13','Kota Payakumbuh','Provinsi Sumatera Barat'],
  ['03','14','Kota Sawahlunto','Provinsi Sumatera Barat'],
  ['03','15','Kota Solok','Provinsi Sumatera Barat'],
  ['03','16','Kota Pariaman','Provinsi Sumatera Barat'],
  ['03','17','Kab. Pasaman Barat','Provinsi Sumatera Barat'],
  ['03','18','Kab. Dharmasraya','Provinsi Sumatera Barat'],
  ['03','19','Kab. Solok Selatan','Provinsi Sumatera Barat'],
  ['04','00','Prov. Riau','Provinsi Riau'],
  ['04','01','Kab. Bengkalis','Provinsi Riau'],
  ['04','02','Kab. Indragiri Hilir','Provinsi Riau'],
  ['04','03','Kab. Indragiri Hulu','Provinsi Riau'],
  ['04','04','Kab. Kampar','Provinsi Riau'],
  ['04','05','Kab. Kuantan Singingi','Provinsi Riau'],
  ['04','06','Kab. Pelalawan','Provinsi Riau'],
  ['04','07','Kab. Rokan Hilir','Provinsi Riau'],
  ['04','08','Kab. Rokan Hulu','Provinsi Riau'],
  ['04','09','Kab. Siak','Provinsi Riau'],
  ['04','10','Kota Dumai','Provinsi Riau'],
  ['04','11','Kota Pekanbaru','Provinsi Riau'],
  ['04','12','Kab. Kepulauan Meranti','Provinsi Riau'],
  ['05','00','Prov. Jambi','Provinsi Jambi'],
  ['05','01','Kab. Batanghari','Provinsi Jambi'],
  ['05','02','Kab. Bungo','Provinsi Jambi'],
  ['05','03','Kab. Kerinci','Provinsi Jambi'],
  ['05','04','Kab. Merangin','Provinsi Jambi'],
  ['05','05','Kab. Muaro Jambi','Provinsi Jambi'],
  ['05','06','Kab. Sarolangun','Provinsi Jambi'],
  ['05','07','Kab. Tanjung Jabung Barat','Provinsi Jambi'],
  ['05','08','Kab. Tanjung Jabung Timur','Provinsi Jambi'],
  ['05','09','Kab. Tebo','Provinsi Jambi'],
  ['05','10','Kota Jambi','Provinsi Jambi'],
  ['05','11','Kota Sungai Penuh','Provinsi Jambi'],
  ['06','00','Prov. Sumatera Selatan','Provinsi Sumatera Selatan'],
  ['06','01','Kab. Lahat','Provinsi Sumatera Selatan'],
  ['06','02','Kab. Musi Banyuasin','Provinsi Sumatera Selatan'],
  ['06','03','Kab. Musi Rawas','Provinsi Sumatera Selatan'],
  ['06','04','Kab. Muara Enim','Provinsi Sumatera Selatan'],
  ['06','05','Kab. Ogan Komering Ilir','Provinsi Sumatera Selatan'],
  ['06','06','Kab. Ogan Komering Ulu','Provinsi Sumatera Selatan'],
  ['06','07','Kota Palembang','Provinsi Sumatera Selatan'],
  ['06','08','Kota Prabumulih','Provinsi Sumatera Selatan'],
  ['06','09','Kota Pagar Alam','Provinsi Sumatera Selatan'],
  ['06','10','Kota Lubuk Linggau','Provinsi Sumatera Selatan'],
  ['06','11','Kab. Banyuasin','Provinsi Sumatera Selatan'],
  ['06','12','Kab. Ogan Ilir','Provinsi Sumatera Selatan'],
  ['06','13','Kab. OKU Timur','Provinsi Sumatera Selatan'],
  ['06','14','Kab. OKU Selatan','Provinsi Sumatera Selatan'],
  ['06','15','Kab. Empat Lawang','Provinsi Sumatera Selatan'],
  ['06','16','Kab. Penukal Abab Lematang Ilir','Provinsi Sumatera Selatan'],
  ['06','17','Kab. Musi Rawas Utara','Provinsi Sumatera Selatan'],
  ['07','00','Prov. Bengkulu','Provinsi Bengkulu'],
  ['07','01','Kab. Bengkulu Selatan','Provinsi Bengkulu'],
  ['07','02','Kab. Bengkulu Utara','Provinsi Bengkulu'],
  ['07','03','Kab. Rejang Lebong','Provinsi Bengkulu'],
  ['07','04','Kota Bengkulu','Provinsi Bengkulu'],
  ['07','05','Kab. Kaur','Provinsi Bengkulu'],
  ['07','06','Kab. Seluma','Provinsi Bengkulu'],
  ['07','07','Kab. Mukomuko','Provinsi Bengkulu'],
  ['07','08','Kab. Lebong','Provinsi Bengkulu'],
  ['07','09','Kab. Kepahiang','Provinsi Bengkulu'],
  ['07','10','Kab. Bengkulu Tengah','Provinsi Bengkulu'],
  ['08','00','Prov. Lampung','Provinsi Lampung'],
  ['08','01','Kab. Lampung Barat','Provinsi Lampung'],
  ['08','02','Kab. Lampung Selatan','Provinsi Lampung'],
  ['08','03','Kab. Lampung Tengah','Provinsi Lampung'],
  ['08','04','Kab. Lampung Utara','Provinsi Lampung'],
  ['08','05','Kab. Lampung Timur','Provinsi Lampung'],
  ['08','06','Kab. Tanggamus','Provinsi Lampung'],
  ['08','07','Kab. Tulang Bawang','Provinsi Lampung'],
  ['08','08','Kab. Way Kanan','Provinsi Lampung'],
  ['08','09','Kota Bandar Lampung','Provinsi Lampung'],
  ['08','10','Kota Metro','Provinsi Lampung'],
  ['08','11','Kab. Pesawaran','Provinsi Lampung'],
  ['08','12','Kab. Pringsewu','Provinsi Lampung'],
  ['08','13','Kab. Mesuji','Provinsi Lampung'],
  ['08','14','Kab. Tulang Bawang Barat','Provinsi Lampung'],
  ['08','15','Kab. Pesisir Barat','Provinsi Lampung'],
  ['09','00','Prov. DKI Jakarta','Provinsi DKI Jakarta'],
  ['10','00','Prov. Jawa Barat','Provinsi Jawa Barat'],
  ['10','01','Kab. Bandung','Provinsi Jawa Barat'],
  ['10','02','Kab. Bekasi','Provinsi Jawa Barat'],
  ['10','03','Kab. Bogor','Provinsi Jawa Barat'],
  ['10','04','Kab. Ciamis','Provinsi Jawa Barat'],
  ['10','05','Kab. Cianjur','Provinsi Jawa Barat'],
  ['10','06','Kab. Cirebon','Provinsi Jawa Barat'],
  ['10','07','Kab. Garut','Provinsi Jawa Barat'],
  ['10','08','Kab. Indramayu','Provinsi Jawa Barat'],
  ['10','09','Kab. Karawang','Provinsi Jawa Barat'],
  ['10','10','Kab. Kuningan','Provinsi Jawa Barat'],
  ['10','11','Kab. Majalengka','Provinsi Jawa Barat'],
  ['10','12','Kab. Purwakarta','Provinsi Jawa Barat'],
  ['10','13','Kab. Subang','Provinsi Jawa Barat'],
  ['10','14','Kab. Sukabumi','Provinsi Jawa Barat'],
  ['10','15','Kab. Sumedang','Provinsi Jawa Barat'],
  ['10','16','Kab. Tasikmalaya','Provinsi Jawa Barat'],
  ['10','17','Kota Bandung','Provinsi Jawa Barat'],
  ['10','18','Kota Bekasi','Provinsi Jawa Barat'],
  ['10','19','Kota Bogor','Provinsi Jawa Barat'],
  ['10','20','Kota Cirebon','Provinsi Jawa Barat'],
  ['10','21','Kota Depok','Provinsi Jawa Barat'],
  ['10','22','Kota Sukabumi','Provinsi Jawa Barat'],
  ['10','23','Kota Tasikmalaya','Provinsi Jawa Barat'],
  ['10','24','Kota Cimahi','Provinsi Jawa Barat'],
  ['10','25','Kota Banjar','Provinsi Jawa Barat'],
  ['10','26','Kab. Bandung Barat','Provinsi Jawa Barat'],
  ['10','27','Kab. Pangandaran','Provinsi Jawa Barat'],
  ['11','00','Prov. Jawa Tengah','Provinsi Jawa Tengah'],
  ['11','01','Kab. Banjarnegara','Provinsi Jawa Tengah'],
  ['11','02','Kab. Banyumas','Provinsi Jawa Tengah'],
  ['11','03','Kab. Batang','Provinsi Jawa Tengah'],
  ['11','04','Kab. Blora','Provinsi Jawa Tengah'],
  ['11','05','Kab. Boyolali','Provinsi Jawa Tengah'],
  ['11','06','Kab. Brebes','Provinsi Jawa Tengah'],
  ['11','07','Kab. Cilacap','Provinsi Jawa Tengah'],
  ['11','08','Kab. Demak','Provinsi Jawa Tengah'],
  ['11','09','Kab. Grobogan','Provinsi Jawa Tengah'],
  ['11','10','Kab. Jepara','Provinsi Jawa Tengah'],
  ['11','11','Kab. Karanganyar','Provinsi Jawa Tengah'],
  ['11','12','Kab. Kebumen','Provinsi Jawa Tengah'],
  ['11','13','Kab. Kendal','Provinsi Jawa Tengah'],
  ['11','14','Kab. Klaten','Provinsi Jawa Tengah'],
  ['11','15','Kab. Kudus','Provinsi Jawa Tengah'],
  ['11','16','Kab. Magelang','Provinsi Jawa Tengah'],
  ['11','17','Kab. Pati','Provinsi Jawa Tengah'],
  ['11','18','Kab. Pekalongan','Provinsi Jawa Tengah'],
  ['11','19','Kab. Pemalang','Provinsi Jawa Tengah'],
  ['11','20','Kab. Purbalingga','Provinsi Jawa Tengah'],
  ['11','21','Kab. Purworejo','Provinsi Jawa Tengah'],
  ['11','22','Kab. Rembang','Provinsi Jawa Tengah'],
  ['11','23','Kab. Semarang','Provinsi Jawa Tengah'],
  ['11','24','Kab. Sragen','Provinsi Jawa Tengah'],
  ['11','25','Kab. Sukoharjo','Provinsi Jawa Tengah'],
  ['11','26','Kab. Tegal','Provinsi Jawa Tengah'],
  ['11','27','Kab. Temanggung','Provinsi Jawa Tengah'],
  ['11','28','Kab. Wonogiri','Provinsi Jawa Tengah'],
  ['11','29','Kab. Wonosobo','Provinsi Jawa Tengah'],
  ['11','30','Kota Magelang','Provinsi Jawa Tengah'],
  ['11','31','Kota Pekalongan','Provinsi Jawa Tengah'],
  ['11','32','Kota Salatiga','Provinsi Jawa Tengah'],
  ['11','33','Kota Semarang','Provinsi Jawa Tengah'],
  ['11','34','Kota Surakarta','Provinsi Jawa Tengah'],
  ['11','35','Kota Tegal','Provinsi Jawa Tengah'],
  ['12','00','Prov. DI Yogyakarta','Provinsi DI Yogyakarta'],
  ['12','01','Kab. Bantul','Provinsi DI Yogyakarta'],
  ['12','02','Kab. Gunung Kidul','Provinsi DI Yogyakarta'],
  ['12','03','Kab. Kulon Progo','Provinsi DI Yogyakarta'],
  ['12','04','Kab. Sleman','Provinsi DI Yogyakarta'],
  ['12','05','Kota Yogyakarta','Provinsi DI Yogyakarta'],
  ['13','00','Prov. Jawa Timur','Provinsi Jawa Timur'],
  ['13','01','Kab. Bangkalan','Provinsi Jawa Timur'],
  ['13','02','Kab. Banyuwangi','Provinsi Jawa Timur'],
  ['13','03','Kab. Blitar','Provinsi Jawa Timur'],
  ['13','04','Kab. Bojonegoro','Provinsi Jawa Timur'],
  ['13','05','Kab. Bondowoso','Provinsi Jawa Timur'],
  ['13','06','Kab. Gresik','Provinsi Jawa Timur'],
  ['13','07','Kab. Jember','Provinsi Jawa Timur'],
  ['13','08','Kab. Jombang','Provinsi Jawa Timur'],
  ['13','09','Kab. Kediri','Provinsi Jawa Timur'],
  ['13','10','Kab. Lamongan','Provinsi Jawa Timur'],
  ['13','11','Kab. Lumajang','Provinsi Jawa Timur'],
  ['13','12','Kab. Madiun','Provinsi Jawa Timur'],
  ['13','13','Kab. Magetan','Provinsi Jawa Timur'],
  ['13','14','Kab. Malang','Provinsi Jawa Timur'],
  ['13','15','Kab. Mojokerto','Provinsi Jawa Timur'],
  ['13','16','Kab. Nganjuk','Provinsi Jawa Timur'],
  ['13','17','Kab. Ngawi','Provinsi Jawa Timur'],
  ['13','18','Kab. Pacitan','Provinsi Jawa Timur'],
  ['13','19','Kab. Pamekasan','Provinsi Jawa Timur'],
  ['13','20','Kab. Pasuruan','Provinsi Jawa Timur'],
  ['13','21','Kab. Ponorogo','Provinsi Jawa Timur'],
  ['13','22','Kab. Probolinggo','Provinsi Jawa Timur'],
  ['13','23','Kab. Sampang','Provinsi Jawa Timur'],
  ['13','24','Kab. Sidoarjo','Provinsi Jawa Timur'],
  ['13','25','Kab. Situbondo','Provinsi Jawa Timur'],
  ['13','26','Kab. Sumenep','Provinsi Jawa Timur'],
  ['13','27','Kab. Trenggalek','Provinsi Jawa Timur'],
  ['13','28','Kab. Tuban','Provinsi Jawa Timur'],
  ['13','29','Kab. Tulungagung','Provinsi Jawa Timur'],
  ['13','30','Kota Blitar','Provinsi Jawa Timur'],
  ['13','31','Kota Kediri','Provinsi Jawa Timur'],
  ['13','32','Kota Madiun','Provinsi Jawa Timur'],
  ['13','33','Kota Malang','Provinsi Jawa Timur'],
  ['13','34','Kota Mojokerto','Provinsi Jawa Timur'],
  ['13','35','Kota Pasuruan','Provinsi Jawa Timur'],
  ['13','36','Kota Probolinggo','Provinsi Jawa Timur'],
  ['13','37','Kota Surabaya','Provinsi Jawa Timur'],
  ['13','38','Kota Batu','Provinsi Jawa Timur'],
  ['14','00','Prov. Kalimantan Barat','Provinsi Kalimantan Barat'],
  ['14','01','Kab. Bengkayang','Provinsi Kalimantan Barat'],
  ['14','02','Kab. Landak','Provinsi Kalimantan Barat'],
  ['14','03','Kab. Kapuas Hulu','Provinsi Kalimantan Barat'],
  ['14','04','Kab. Ketapang','Provinsi Kalimantan Barat'],
  ['14','05','Kab. Pontianak','Provinsi Kalimantan Barat'],
  ['14','06','Kab. Sambas','Provinsi Kalimantan Barat'],
  ['14','07','Kab. Sanggau','Provinsi Kalimantan Barat'],
  ['14','08','Kab. Sintang','Provinsi Kalimantan Barat'],
  ['14','09','Kota Pontianak','Provinsi Kalimantan Barat'],
  ['14','10','Kota Singkawang','Provinsi Kalimantan Barat'],
  ['14','11','Kab. Sekadau','Provinsi Kalimantan Barat'],
  ['14','12','Kab. Melawi','Provinsi Kalimantan Barat'],
  ['14','13','Kab. Kayong Utara','Provinsi Kalimantan Barat'],
  ['14','14','Kab. Kubu Raya','Provinsi Kalimantan Barat'],
  ['15','00','Prov. Kalimantan Tengah','Provinsi Kalimantan Tengah'],
  ['15','01','Kab. Barito Selatan','Provinsi Kalimantan Tengah'],
  ['15','02','Kab. Barito Utara','Provinsi Kalimantan Tengah'],
  ['15','03','Kab. Kapuas','Provinsi Kalimantan Tengah'],
  ['15','04','Kab. Kotawaringin Barat','Provinsi Kalimantan Tengah'],
  ['15','05','Kab. Kotawaringin Timur','Provinsi Kalimantan Tengah'],
  ['15','06','Kota Palangkaraya','Provinsi Kalimantan Tengah'],
  ['15','07','Kab. Katingan','Provinsi Kalimantan Tengah'],
  ['15','08','Kab. Seruyan','Provinsi Kalimantan Tengah'],
  ['15','09','Kab. Sukamara','Provinsi Kalimantan Tengah'],
  ['15','10','Kab. Lamandau','Provinsi Kalimantan Tengah'],
  ['15','11','Kab. Gunung Mas','Provinsi Kalimantan Tengah'],
  ['15','12','Kab. Pulang Pisau','Provinsi Kalimantan Tengah'],
  ['15','13','Kab. Murung Raya','Provinsi Kalimantan Tengah'],
  ['15','14','Kab. Barito Timur','Provinsi Kalimantan Tengah'],
  ['16','00','Prov. Kalimantan Selatan','Provinsi Kalimantan Selatan'],
  ['16','01','Kab. Banjar','Provinsi Kalimantan Selatan'],
  ['16','02','Kab. Barito Kuala','Provinsi Kalimantan Selatan'],
  ['16','03','Kab. Hulu Sungai Selatan','Provinsi Kalimantan Selatan'],
  ['16','04','Kab. Hulu Sungai Tengah','Provinsi Kalimantan Selatan'],
  ['16','05','Kab. Hulu Sungai Utara','Provinsi Kalimantan Selatan'],
  ['16','06','Kab. Kotabaru','Provinsi Kalimantan Selatan'],
  ['16','07','Kab. Tabalong','Provinsi Kalimantan Selatan'],
  ['16','08','Kab. Tanah Laut','Provinsi Kalimantan Selatan'],
  ['16','09','Kab. Tapin','Provinsi Kalimantan Selatan'],
  ['16','10','Kota Banjarbaru','Provinsi Kalimantan Selatan'],
  ['16','11','Kota Banjarmasin','Provinsi Kalimantan Selatan'],
  ['16','12','Kab. Balangan','Provinsi Kalimantan Selatan'],
  ['16','13','Kab. Tanah Bumbu','Provinsi Kalimantan Selatan'],
  ['17','00','Prov. Kalimantan Timur','Provinsi Kalimantan Timur'],
  ['17','01','Kab. Berau','Provinsi Kalimantan Timur'],
  ['17','03','Kab. Kutai Kartanegara','Provinsi Kalimantan Timur'],
  ['17','04','Kab. Kutai Barat','Provinsi Kalimantan Timur'],
  ['17','05','Kab. Kutai Timur','Provinsi Kalimantan Timur'],
  ['17','08','Kab. Paser','Provinsi Kalimantan Timur'],
  ['17','09','Kota Balikpapan','Provinsi Kalimantan Timur'],
  ['17','10','Kota Bontang','Provinsi Kalimantan Timur'],
  ['17','11','Kota Samarinda','Provinsi Kalimantan Timur'],
  ['17','13','Kab. Penajam Paser Utara','Provinsi Kalimantan Timur'],
  ['17','15','Kab. Mahakam Ulu','Provinsi Kalimantan Timur'],
  ['18','00','Prov. Sulawesi Utara','Provinsi Sulawesi Utara'],
  ['18','01','Kab. Bolaang Mongondow','Provinsi Sulawesi Utara'],
  ['18','02','Kab. Minahasa','Provinsi Sulawesi Utara'],
  ['18','03','Kab. Sangihe','Provinsi Sulawesi Utara'],
  ['18','04','Kota Bitung','Provinsi Sulawesi Utara'],
  ['18','05','Kota Manado','Provinsi Sulawesi Utara'],
  ['18','06','Kab. Kepulauan Talaud','Provinsi Sulawesi Utara'],
  ['18','07','Kab. Minahasa Selatan','Provinsi Sulawesi Utara'],
  ['18','08','Kota Tomohon','Provinsi Sulawesi Utara'],
  ['18','09','Kab. Minahasa Utara','Provinsi Sulawesi Utara'],
  ['18','10','Kab. Kep. Siau Tagulandang Biaro','Provinsi Sulawesi Utara'],
  ['18','11','Kota Kotamobagu','Provinsi Sulawesi Utara'],
  ['18','12','Kab. Bolaang Mongondow Utara','Provinsi Sulawesi Utara'],
  ['18','13','Kab. Minahasa Tenggara','Provinsi Sulawesi Utara'],
  ['18','14','Kab. Bolaang Mongondow Timur','Provinsi Sulawesi Utara'],
  ['18','15','Kab. Bolaang Mongondow Selatan','Provinsi Sulawesi Utara'],
  ['19','00','Prov. Sulawesi Tengah','Provinsi Sulawesi Tengah'],
  ['19','01','Kab. Banggai','Provinsi Sulawesi Tengah'],
  ['19','02','Kab. Banggai Kepulauan','Provinsi Sulawesi Tengah'],
  ['19','03','Kab. Buol','Provinsi Sulawesi Tengah'],
  ['19','04','Kab. Toli-Toli','Provinsi Sulawesi Tengah'],
  ['19','05','Kab. Donggala','Provinsi Sulawesi Tengah'],
  ['19','06','Kab. Morowali','Provinsi Sulawesi Tengah'],
  ['19','07','Kab. Poso','Provinsi Sulawesi Tengah'],
  ['19','08','Kota Palu','Provinsi Sulawesi Tengah'],
  ['19','09','Kab. Parigi Moutong','Provinsi Sulawesi Tengah'],
  ['19','10','Kab. Tojo Una Una','Provinsi Sulawesi Tengah'],
  ['19','11','Kab. Sigi','Provinsi Sulawesi Tengah'],
  ['19','12','Kab. Banggai Laut','Provinsi Sulawesi Tengah'],
  ['19','13','Kab. Morowali Utara','Provinsi Sulawesi Tengah'],
  ['20','00','Prov. Sulawesi Selatan','Provinsi Sulawesi Selatan'],
  ['20','01','Kab. Bantaeng','Provinsi Sulawesi Selatan'],
  ['20','02','Kab. Barru','Provinsi Sulawesi Selatan'],
  ['20','03','Kab. Bone','Provinsi Sulawesi Selatan'],
  ['20','04','Kab. Bulukumba','Provinsi Sulawesi Selatan'],
  ['20','05','Kab. Enrekang','Provinsi Sulawesi Selatan'],
  ['20','06','Kab. Gowa','Provinsi Sulawesi Selatan'],
  ['20','07','Kab. Jeneponto','Provinsi Sulawesi Selatan'],
  ['20','08','Kab. Luwu','Provinsi Sulawesi Selatan'],
  ['20','09','Kab. Luwu Utara','Provinsi Sulawesi Selatan'],
  ['20','10','Kab. Maros','Provinsi Sulawesi Selatan'],
  ['20','11','Kab. Pangkajene Kepulauan','Provinsi Sulawesi Selatan'],
  ['20','12','Kota Palopo','Provinsi Sulawesi Selatan'],
  ['20','13','Kab. Luwu Timur','Provinsi Sulawesi Selatan'],
  ['20','14','Kab. Pinrang','Provinsi Sulawesi Selatan'],
  ['20','15','Kab. Sinjai','Provinsi Sulawesi Selatan'],
  ['20','16','Kab. Kepulauan Selayar','Provinsi Sulawesi Selatan'],
  ['20','17','Kab. Sidenreng Rappang','Provinsi Sulawesi Selatan'],
  ['20','19','Kab. Soppeng','Provinsi Sulawesi Selatan'],
  ['20','20','Kab. Takalar','Provinsi Sulawesi Selatan'],
  ['20','21','Kab. Tana Toraja','Provinsi Sulawesi Selatan'],
  ['20','22','Kab. Wajo','Provinsi Sulawesi Selatan'],
  ['20','23','Kota Pare-pare','Provinsi Sulawesi Selatan'],
  ['20','24','Kota Makassar','Provinsi Sulawesi Selatan'],
  ['20','25','Kab. Toraja Utara','Provinsi Sulawesi Selatan'],
  ['21','00','Prov. Sulawesi Tenggara','Provinsi Sulawesi Tenggara'],
  ['21','01','Kab. Buton','Provinsi Sulawesi Tenggara'],
  ['21','02','Kab. Konawe','Provinsi Sulawesi Tenggara'],
  ['21','03','Kab. Kolaka','Provinsi Sulawesi Tenggara'],
  ['21','04','Kab. Muna','Provinsi Sulawesi Tenggara'],
  ['21','05','Kota Kendari','Provinsi Sulawesi Tenggara'],
  ['21','06','Kota Bau-bau','Provinsi Sulawesi Tenggara'],
  ['21','07','Kab. Konawe Selatan','Provinsi Sulawesi Tenggara'],
  ['21','08','Kab. Bombana','Provinsi Sulawesi Tenggara'],
  ['21','09','Kab. Wakatobi','Provinsi Sulawesi Tenggara'],
  ['21','10','Kab. Kolaka Utara','Provinsi Sulawesi Tenggara'],
  ['21','11','Kab. Konawe Utara','Provinsi Sulawesi Tenggara'],
  ['21','12','Kab. Buton Utara','Provinsi Sulawesi Tenggara'],
  ['21','13','Kab. Konawe Kepulauan','Provinsi Sulawesi Tenggara'],
  ['21','14','Kab. Kolaka Timur','Provinsi Sulawesi Tenggara'],
  ['21','15','Kab. Muna Barat','Provinsi Sulawesi Tenggara'],
  ['21','16','Kab. Buton Tengah','Provinsi Sulawesi Tenggara'],
  ['21','17','Kab. Buton Selatan','Provinsi Sulawesi Tenggara'],
  ['22','00','Prov. Bali','Provinsi Bali'],
  ['22','01','Kab. Badung','Provinsi Bali'],
  ['22','02','Kab. Bangli','Provinsi Bali'],
  ['22','03','Kab. Buleleng','Provinsi Bali'],
  ['22','04','Kab. Gianyar','Provinsi Bali'],
  ['22','05','Kab. Jembrana','Provinsi Bali'],
  ['22','06','Kab. Karangasem','Provinsi Bali'],
  ['22','07','Kab. Klungkung','Provinsi Bali'],
  ['22','08','Kab. Tabanan','Provinsi Bali'],
  ['22','09','Kota Denpasar','Provinsi Bali'],
  ['23','00','Prov. Nusa Tenggara Barat','Provinsi Nusa Tenggara Barat'],
  ['23','01','Kab. Bima','Provinsi Nusa Tenggara Barat'],
  ['23','02','Kab. Dompu','Provinsi Nusa Tenggara Barat'],
  ['23','03','Kab. Lombok Barat','Provinsi Nusa Tenggara Barat'],
  ['23','04','Kab. Lombok Tengah','Provinsi Nusa Tenggara Barat'],
  ['23','05','Kab. Lombok Timur','Provinsi Nusa Tenggara Barat'],
  ['23','06','Kab. Sumbawa','Provinsi Nusa Tenggara Barat'],
  ['23','07','Kota Mataram','Provinsi Nusa Tenggara Barat'],
  ['23','08','Kota Bima','Provinsi Nusa Tenggara Barat'],
  ['23','09','Kab. Sumbawa Barat','Provinsi Nusa Tenggara Barat'],
  ['23','10','Kab. Lombok Utara','Provinsi Nusa Tenggara Barat'],
  ['24','00','Prov. Nusa Tenggara Timur','Provinsi Nusa Tenggara Timur'],
  ['24','01','Kab. Alor','Provinsi Nusa Tenggara Timur'],
  ['24','02','Kab. Belu','Provinsi Nusa Tenggara Timur'],
  ['24','03','Kab. Ende','Provinsi Nusa Tenggara Timur'],
  ['24','04','Kab. Flores Timur','Provinsi Nusa Tenggara Timur'],
  ['24','05','Kab. Kupang','Provinsi Nusa Tenggara Timur'],
  ['24','06','Kab. Lembata','Provinsi Nusa Tenggara Timur'],
  ['24','07','Kab. Manggarai','Provinsi Nusa Tenggara Timur'],
  ['24','08','Kab. Ngada','Provinsi Nusa Tenggara Timur'],
  ['24','09','Kab. Sikka','Provinsi Nusa Tenggara Timur'],
  ['24','10','Kab. Sumba Barat','Provinsi Nusa Tenggara Timur'],
  ['24','11','Kab. Sumba Timur','Provinsi Nusa Tenggara Timur'],
  ['24','12','Kab. Timor Tengah Selatan','Provinsi Nusa Tenggara Timur'],
  ['24','13','Kab. Timor Tengah Utara','Provinsi Nusa Tenggara Timur'],
  ['24','14','Kota Kupang','Provinsi Nusa Tenggara Timur'],
  ['24','15','Kab. Rote Ndao','Provinsi Nusa Tenggara Timur'],
  ['24','16','Kab. Manggarai Barat','Provinsi Nusa Tenggara Timur'],
  ['24','17','Kab. Nagekeo','Provinsi Nusa Tenggara Timur'],
  ['24','18','Kab. Sumba Barat Daya','Provinsi Nusa Tenggara Timur'],
  ['24','19','Kab. Sumba Tengah','Provinsi Nusa Tenggara Timur'],
  ['24','20','Kab. Manggarai Timur','Provinsi Nusa Tenggara Timur'],
  ['24','21','Kab. Sabu Raijua','Provinsi Nusa Tenggara Timur'],
  ['24','22','Kab. Malaka','Provinsi Nusa Tenggara Timur'],
  ['25','00','Prov. Maluku','Provinsi Maluku'],
  ['25','01','Kab. Kep. Tanimbar','Provinsi Maluku'],
  ['25','02','Kab. Maluku Tengah','Provinsi Maluku'],
  ['25','03','Kab. Maluku Tenggara','Provinsi Maluku'],
  ['25','04','Kab. Buru','Provinsi Maluku'],
  ['25','05','Kota Ambon','Provinsi Maluku'],
  ['25','06','Kab. Seram Bagian Barat','Provinsi Maluku'],
  ['25','07','Kab. Seram Bagian Timur','Provinsi Maluku'],
  ['25','08','Kab. Kepulauan Aru','Provinsi Maluku'],
  ['25','09','Kota Tual','Provinsi Maluku'],
  ['25','10','Kab. Maluku Barat Daya','Provinsi Maluku'],
  ['25','11','Kab. Buru Selatan','Provinsi Maluku'],
  ['26','00','Prov. Papua','Provinsi Papua'],
  ['26','01','Kab. Biak Numfor','Provinsi Papua'],
  ['26','02','Kab. Jayapura','Provinsi Papua'],
  ['26','09','Kab. Kepulauan Yapen','Provinsi Papua'],
  ['26','10','Kota Jayapura','Provinsi Papua'],
  ['26','11','Kab. Sarmi','Provinsi Papua'],
  ['26','12','Kab. Keerom','Provinsi Papua'],
  ['26','19','Kab. Waropen','Provinsi Papua'],
  ['26','20','Kab. Supiori','Provinsi Papua'],
  ['26','21','Kab. Mamberamo Raya','Provinsi Papua'],
  ['27','00','Prov. Maluku Utara','Provinsi Maluku Utara'],
  ['27','01','Kab. Halmahera Tengah','Provinsi Maluku Utara'],
  ['27','02','Kota Ternate','Provinsi Maluku Utara'],
  ['27','03','Kab. Halmahera Barat','Provinsi Maluku Utara'],
  ['27','04','Kab. Halmahera Timur','Provinsi Maluku Utara'],
  ['27','05','Kab. Halmahera Selatan','Provinsi Maluku Utara'],
  ['27','06','Kab. Halmahera Utara','Provinsi Maluku Utara'],
  ['27','07','Kab. Kepulauan Sula','Provinsi Maluku Utara'],
  ['27','08','Kota Tidore Kepulauan','Provinsi Maluku Utara'],
  ['27','09','Kab. Pulau Morotai','Provinsi Maluku Utara'],
  ['27','10','Kab. Pulau Taliabu','Provinsi Maluku Utara'],
  ['28','00','Prov. Banten','Provinsi Banten'],
  ['28','01','Kab. Lebak','Provinsi Banten'],
  ['28','02','Kab. Pandeglang','Provinsi Banten'],
  ['28','03','Kab. Serang','Provinsi Banten'],
  ['28','04','Kab. Tangerang','Provinsi Banten'],
  ['28','05','Kota Cilegon','Provinsi Banten'],
  ['28','06','Kota Tangerang','Provinsi Banten'],
  ['28','07','Kota Serang','Provinsi Banten'],
  ['28','08','Kota Tangerang Selatan','Provinsi Banten'],
  ['29','00','Prov. Bangka Belitung','Provinsi Bangka Belitung'],
  ['29','01','Kab. Bangka','Provinsi Bangka Belitung'],
  ['29','02','Kab. Belitung','Provinsi Bangka Belitung'],
  ['29','03','Kota Pangkal Pinang','Provinsi Bangka Belitung'],
  ['29','04','Kab. Bangka Selatan','Provinsi Bangka Belitung'],
  ['29','05','Kab. Bangka Tengah','Provinsi Bangka Belitung'],
  ['29','06','Kab. Bangka Barat','Provinsi Bangka Belitung'],
  ['29','07','Kab. Belitung Timur','Provinsi Bangka Belitung'],
  ['30','00','Prov. Gorontalo','Provinsi Gorontalo'],
  ['30','01','Kab. Boalemo','Provinsi Gorontalo'],
  ['30','02','Kab. Gorontalo','Provinsi Gorontalo'],
  ['30','03','Kota Gorontalo','Provinsi Gorontalo'],
  ['30','04','Kab. Pohuwato','Provinsi Gorontalo'],
  ['30','05','Kab. Bone Bolango','Provinsi Gorontalo'],
  ['30','06','Kab. Gorontalo Utara','Provinsi Gorontalo'],
  ['31','00','Prov. Kepulauan Riau','Provinsi Kepulauan Riau'],
  ['31','01','Kab. Natuna','Provinsi Kepulauan Riau'],
  ['31','02','Kab. Kepulauan Anambas','Provinsi Kepulauan Riau'],
  ['31','03','Kab. Karimun','Provinsi Kepulauan Riau'],
  ['31','04','Kota Batam','Provinsi Kepulauan Riau'],
  ['31','05','Kota Tanjung Pinang','Provinsi Kepulauan Riau'],
  ['31','06','Kab. Lingga','Provinsi Kepulauan Riau'],
  ['31','07','Kab. Bintan','Provinsi Kepulauan Riau'],
  ['32','00','Prov. Papua Barat','Provinsi Papua Barat'],
  ['32','01','Kab. FakFak','Provinsi Papua Barat'],
  ['32','02','Kab. Manokwari','Provinsi Papua Barat'],
  ['32','07','Kab. Teluk Bintuni','Provinsi Papua Barat'],
  ['32','08','Kab. Teluk Wondama','Provinsi Papua Barat'],
  ['32','09','Kab. Kaimana','Provinsi Papua Barat'],
  ['32','12','Kab. Manokwari Selatan','Provinsi Papua Barat'],
  ['32','13','Kab. Pegunungan Arfak','Provinsi Papua Barat'],
  ['33','00','Prov. Sulawesi Barat','Provinsi Sulawesi Barat'],
  ['33','01','Kab. Majene','Provinsi Sulawesi Barat'],
  ['33','02','Kab. Mamuju','Provinsi Sulawesi Barat'],
  ['33','03','Kab. Polewali Mandar','Provinsi Sulawesi Barat'],
  ['33','04','Kab. Mamasa','Provinsi Sulawesi Barat'],
  ['33','05','Kab. Pasangkayu','Provinsi Sulawesi Barat'],
  ['33','06','Kab. Mamuju Tengah','Provinsi Sulawesi Barat'],
  ['34','00','Prov. Kalimantan Utara','Provinsi Kalimantan Utara'],
  ['34','01','Kab. Bulungan','Provinsi Kalimantan Utara'],
  ['34','02','Kab. Malinau','Provinsi Kalimantan Utara'],
  ['34','03','Kab. Nunukan','Provinsi Kalimantan Utara'],
  ['34','04','Kota Tarakan','Provinsi Kalimantan Utara'],
  ['34','05','Kab. Tana Tidung','Provinsi Kalimantan Utara'],
  ['35','00','Prov. Papua Selatan','Provinsi Papua Selatan'],
  ['35','01','Kab. Merauke','Provinsi Papua Selatan'],
  ['35','02','Kab. Boven Digoel','Provinsi Papua Selatan'],
  ['35','03','Kab. Mappi','Provinsi Papua Selatan'],
  ['35','04','Kab. Asmat','Provinsi Papua Selatan'],
  ['36','00','Prov. Papua Tengah','Provinsi Papua Tengah'],
  ['36','01','Kab. Mimika','Provinsi Papua Tengah'],
  ['36','02','Kab. Nabire','Provinsi Papua Tengah'],
  ['36','03','Kab. Paniai','Provinsi Papua Tengah'],
  ['36','04','Kab. Puncak Jaya','Provinsi Papua Tengah'],
  ['36','05','Kab. Dogiyai','Provinsi Papua Tengah'],
  ['36','06','Kab. Puncak','Provinsi Papua Tengah'],
  ['36','07','Kab. Intan Jaya','Provinsi Papua Tengah'],
  ['36','08','Kab. Deiyai','Provinsi Papua Tengah'],
  ['37','00','Prov. Papua Pegunungan','Provinsi Papua Pegunungan'],
  ['37','01','Kab. Jayawijaya','Provinsi Papua Pegunungan'],
  ['37','02','Kab. Yahukimo','Provinsi Papua Pegunungan'],
  ['37','03','Kab. Pegunungan Bintang','Provinsi Papua Pegunungan'],
  ['37','04','Kab. Tolikara','Provinsi Papua Pegunungan'],
  ['37','05','Kab. Mamberamo Tengah','Provinsi Papua Pegunungan'],
  ['37','06','Kab. Yalimo','Provinsi Papua Pegunungan'],
  ['37','07','Kab. Lanny Jaya','Provinsi Papua Pegunungan'],
  ['37','08','Kab. Nduga','Provinsi Papua Pegunungan'],
  ['38','00','Prov. Papua Barat Daya','Provinsi Papua Barat Daya'],
  ['38','01','Kab. Sorong','Provinsi Papua Barat Daya'],
  ['38','02','Kota Sorong','Provinsi Papua Barat Daya'],
  ['38','03','Kab. Raja Ampat','Provinsi Papua Barat Daya'],
  ['38','04','Kab. Sorong Selatan','Provinsi Papua Barat Daya'],
  ['38','05','Kab. Maybrat','Provinsi Papua Barat Daya'],
  ['38','06','Kab. Tambrauw','Provinsi Papua Barat Daya']
];
